### ISSUE TITLE
是不是被加密了

### ISSUE THREAD

**Issue by Sn0r1axi** [bigsk05/YuanArithmetic#2]
[17:21:48.195][192.168.100.13:48728] server connect xyks.yuanfudao.com:443 (8.141.20.129:443)
192.168.100.13:48726: GET https://leo.fbcontent.cn/bh5/leo-web-oral-pk/media/right.1a6f55f7.mp3 HTTP/2.0
          << HTTP/2.0 304 Not Modified 0b
192.168.100.13:48726: GET https://leo.fbcontent.cn/bh5/leo-web-oral-pk/media/wrong.5fc68032.mp3 HTTP/2.0
          << HTTP/2.0 304 Not Modified 0b
[17:21:48.341] Addon error: UnicodeDecodeError when decoding b'\xcb\xb2 with 'utf-8': UnicodeDecodeError('utf-8', b'\xcb\xb2\xa9\xb7)\xe0\xa4k\xa0\x1a\x8fs\x16\xae\x8e\xf0\x8e\xce&\x9f\xed\x08_\xc3\x1f\xe3\xd4\xdd\xb1P\xbf:\xd8p\xca\x92Z\x1b.\x80A\xf2d\x1c\xe7\xb5\xffLE\xc2\xfc\xf2<S\xed\xe6\x004\x03\xfe6\x0c2\xde:\x99\xbf\xab\x97Y\x01:\x93\x84\x8c\xdf\xed0h\xaf\x91\xc6G\xca\\\xf3\x03\xa5\x7f\xcf\xca\xdf/cp\xab\x83\xd3\xc5\x8a\xae\xbfi\xeaw\xa6\xe3\xf4\xe1;\xa0\xb5\x16Q\xcc~\xedms\xd4K\x08\xa4"\x90\xb4{\xb1(t+\n\'\xf6&\xf2k\xb5\xe8\x92\x97\t\x9e\xd0\xd3\xf2L6/\x8f\xa4M}"\xa6\xbf\x9f\xe0N\tB\'<OL\xfbZx\xa3\x1b\xd0\xc6-\xa1\xcd\x19P7\x03\xdc/F`z:\x7fp\xc9\xca\xdd\x05\x85\xf3sE\xe7\xaa?\x9b\xfd*\x1b\xac\xe68\xe5\xce\xe4\xcdCK\xaf\x8dO\xe2\xa8\xb1X\x1f`\x02\xfaW\x032\xe8r\xd6\xb9&h\xfb^]\xe8|\xfe\xd8`\xb7K@i=T\xeb\x1d\x89P)\x8cX\x8d\x1f\x91\xd2L4|\xb1g\xdd\xee\xd8.\xadr\x91;FL~\xdc\xf6t\xa2qbA\xeb|\xd1\x95\xa79\x1e\xce\xca\'E\xff"\x8a\x8e \xfcSx1\x9a\x98/yg\xf8\x9f~\xd0\x9e\xf7\x194\xcb3\xc3\xa2~2\xc08\x0e3\xe3\x91$N\xba\x03\xe6\'\xf24\xe4\xc1f\x87o\xa4*\x10\xd9\xbd\xb1\xaf\x9cZ\x80\xf1\x06u[v7e S\xef"\xc0\xa5\x85xW\xa2\x00\xe7\xe1DT\xcd\x9d\xc6v\xff\xa4F\xd0L\x94\x89\x07\x176\xc5\xd7S\x83~\x90D;\\\xba\x0f\xf8\x12\xc3\x18\x06[\xbe$\xdf\xbf/\xe8\x13o\x0e-\xac\x18\x89\xc2\xb1K>\x01\xfc\xb4=\xc2\x19\x97V\xd7\xc8\x82\xa6\xf7\xbf^\x02\xa7\xf2z\xc1\xd7\xfa\x0bjJ\t\xc6s\x0e\x06C\xe7\x11\xb3\x1dd\xe4p\xe2\t\xae\x8dF\xfdj\xd5Y\xce \xef\x87\x1f\xe8b!\xe7\xf6\x1d\xa3j\x05Mf\x80y\x82g\xca\x0b\xb9>\x10\xea\xf8\x94\x16_c\x8fQ0fFGw<\xfa\xf5(i\x9c\x96\xc3\xcf&\xcd\x9a', 2, 3, 'invalid start byte')
Traceback (most recent call last):
  File "C:\Users\Wangu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\mitmproxy\net\encoding.py", line 62, in decode
    decoded = custom_decode[encoding](encoded)
              ~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'utf-8'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wangu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\mitmproxy\net\encoding.py", line 64, in decode
    decoded = codecs.decode(encoded, encoding, errors)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 2: invalid start byte
decoding with 'utf-8' codec failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\OneDrive\Visual Studio Code\xiaoyuan\YuanArithmetic-main\篡改答案\one_sec.py", line 40, in response
    threading.Thread(target=answer_write, args=(len(re.findall(r'answers', flow.response.text)),)).start()
                                                                           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Wangu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\mitmproxy\http.py", line 352, in text
    return self.get_text()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Wangu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\mitmproxy\http.py", line 435, in get_text
    return cast(str, encoding.decode(content, enc))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Wangu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\mitmproxy\net\encoding.py", line 71, in decode
    raise ValueError(
ValueError: UnicodeDecodeError when decoding b'\xcb\xb2 with 'utf-8': UnicodeDecodeError('utf-8', b'\xcb\xb2\xa9\xb7)\xe0\xa4k\xa0\x1a\x8fs\x16\xae\x8e\xf0\x8e\xce&\x9f\xed\x08_\xc3\x1f\xe3\xd4\xdd\xb1P\xbf:\xd8p\xca\x92Z\x1b.\x80A\xf2d\x1c\xe7\xb5\xffLE\xc2\xfc\xf2<S\xed\xe6\x004\x03\xfe6\x0c2\xde:\x99\xbf\xab\x97Y\x01:\x93\x84\x8c\xdf\xed0h\xaf\x91\xc6G\xca\\\xf3\x03\xa5\x7f\xcf\xca\xdf/cp\xab\x83\xd3\xc5\x8a\xae\xbfi\xeaw\xa6\xe3\xf4\xe1;\xa0\xb5\x16Q\xcc~\xedms\xd4K\x08\xa4"\x90\xb4{\xb1(t+\n\'\xf6&\xf2k\xb5\xe8\x92\x97\t\x9e\xd0\xd3\xf2L6/\x8f\xa4M}"\xa6\xbf\x9f\xe0N\tB\'<OL\xfbZx\xa3\x1b\xd0\xc6-\xa1\xcd\x19P7\x03\xdc/F`z:\x7fp\xc9\xca\xdd\x05\x85\xf3sE\xe7\xaa?\x9b\xfd*\x1b\xac\xe68\xe5\xce\xe4\xcdCK\xaf\x8dO\xe2\xa8\xb1X\x1f`\x02\xfaW\x032\xe8r\xd6\xb9&h\xfb^]\xe8|\xfe\xd8`\xb7K@i=T\xeb\x1d\x89P)\x8cX\x8d\x1f\x91\xd2L4|\xb1g\xdd\xee\xd8.\xadr\x91;FL~\xdc\xf6t\xa2qbA\xeb|\xd1\x95\xa79\x1e\xce\xca\'E\xff"\x8a\x8e \xfcSx1\x9a\x98/yg\xf8\x9f~\xd0\x9e\xf7\x194\xcb3\xc3\xa2~2\xc08\x0e3\xe3\x91$N\xba\x03\xe6\'\xf24\xe4\xc1f\x87o\xa4*\x10\xd9\xbd\xb1\xaf\x9cZ\x80\xf1\x06u[v7e S\xef"\xc0\xa5\x85xW\xa2\x00\xe7\xe1DT\xcd\x9d\xc6v\xff\xa4F\xd0L\x94\x89\x07\x176\xc5\xd7S\x83~\x90D;\\\xba\x0f\xf8\x12\xc3\x18\x06[\xbe$\xdf\xbf/\xe8\x13o\x0e-\xac\x18\x89\xc2\xb1K>\x01\xfc\xb4=\xc2\x19\x97V\xd7\xc8\x82\xa6\xf7\xbf^\x02\xa7\xf2z\xc1\xd7\xfa\x0bjJ\t\xc6s\x0e\x06C\xe7\x11\xb3\x1dd\xe4p\xe2\t\xae\x8dF\xfdj\xd5Y\xce \xef\x87\x1f\xe8b!\xe7\xf6\x1d\xa3j\x05Mf\x80y\x82g\xca\x0b\xb9>\x10\xea\xf8\x94\x16_c\x8fQ0fFGw<\xfa\xf5(i\x9c\x96\xc3\xcf&\xcd\x9a', 2, 3, 'invalid start byte')

**Comment by Herobetrine** [comment]
是的，被加密了，我也这个报错

**Comment by Moraxyc** [comment]
https://github.com/xmexg/xyks/issues/9
